export const singleMealSearchMock = {
  meals: [
    {
      idMeal: '53026',
      strMeal: 'Tamiya',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Egyptian',
      strInstructions: (`oak the beans in water to cover overnight.Drain. If skinless 
        beans are unavailable, rub to loosen the skins, then discard the skins. Pat the 
        beans dry with a towel.\r\nGrind the beans in a food mill or meat grinder.If 
        neither appliance is available, process them in a food processor but only until 
        the beans form a paste. (If blended too smoothly, the batter tends to fall apart 
        during cooking.) Add the scallions, garlic, cilantro, cumin, baking powder, 
        cayenne, salt, pepper, and coriander, if using.  Refrigerate for at least 30 
        minutes.\r\nShape the bean mixture into 1-inch balls.Flatten slightly and coat 
        with flour.\r\nHeat at least 1½-inches of oil over medium heat to 365 degrees.
        \r\nFry the patties in batches, turning once, until golden brown on all sides, 
        about 5 minutes.Remove with a wire mesh skimmer or slotted spoon. Serve as part 
        of a meze or in pita bread with tomato-cucumber salad and tahina sauce.`),
      strMealThumb: 'https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=mulqW-J3Yy4',
      strIngredient1: 'Broad Beans',
      strIngredient2: 'Spring Onions',
      strIngredient3: 'Garlic Clove',
      strIngredient4: 'Parsley',
      strIngredient5: 'Cumin',
      strIngredient6: 'Baking Powder',
      strIngredient7: 'Cayenne Pepper',
      strIngredient8: 'Flour',
      strIngredient9: 'Vegetable Oil',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '3 cups ',
      strMeasure2: '6',
      strMeasure3: '4',
      strMeasure4: '1/4 cup',
      strMeasure5: '2 tsp',
      strMeasure6: '1 tsp ',
      strMeasure7: '1/2 tsp',
      strMeasure8: 'Spinkling',
      strMeasure9: 'As required',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://oukosher.org/recipes/tamiya-egyptian-dried-fava-bean-fritters/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const singleDrinkSearchMock = {
  drinks: [
    {
      idDrink: '14610',
      strDrink: 'ACID',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Shot',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Shot glass',
      strInstructions: (`Poor in the 151 first followed by the 101 served with 
        a Coke or Dr Pepper chaser.`),
      strInstructionsES: (`Vierta primero el Bacardi 151, seguido del Wild Turkey 
        101 y sirva con Coca-Cola o Dr Pepper.`),
      strInstructionsDE: (`Gering den 151 gefolgt von der 101, die mit einer Cola 
        oder Dr. Pepper Chaser serviert wird.`),
      strInstructionsFR: null,
      strInstructionsIT: (`Versa prima il Bacardi 151 seguito dal 101, servito con 
        una Coca-Cola.`),
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/xuxpxt1479209317.jpg',
      strIngredient1: '151 proof rum',
      strIngredient2: 'Wild Turkey',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 oz Bacardi ',
      strMeasure2: '1 oz ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2016-11-15 11:28:37',
    },
  ],
};
